import { sesorisStore, type Sellable, type Store } from '@/lib/checkout';
import livehappypetCatalog from '@/data/stores/livehappypet.json';

// Partner storefronts that check out through this backend (same PayPal account, their own brand name).
// ponytail: the catalog JSON is generated by D:/Projects/Livehappypet/scripts/build-shop.py; regenerate, don't hand-edit.
const lhp = new Map((livehappypetCatalog as Sellable[]).map((s) => [s.sku, s]));

export const livehappypetStore: Store = {
  id: 'livehappypet',
  brand: 'Livehappypet',
  lookup: (sku) => lhp.get(sku),
  shipping: () => 0, // free US shipping on every order, as the site promises
};

const STORES: Record<string, Store> = { sesoris: sesorisStore, livehappypet: livehappypetStore };

/** Browser origins allowed to call the checkout API for a partner store. */
const ORIGINS: Record<string, string> = {
  'https://www.livehappypet.com': 'livehappypet',
  'https://livehappypet.com': 'livehappypet',
};

export function storeById(id: string | undefined): Store {
  const s = STORES[id ?? 'sesoris'];
  if (!s) throw new Error('Unknown store');
  return s;
}

export function corsHeaders(origin: string | null): Record<string, string> {
  if (!origin || !ORIGINS[origin]) return {};
  return {
    'Access-Control-Allow-Origin': origin,
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type',
    'Access-Control-Max-Age': '86400',
    Vary: 'Origin',
  };
}

/** Store tag + coupon are carried on the PayPal order so capture can re-price it. Old orders used "coupon:CODE". */
export function encodeCustomId(storeId: string, coupon?: string): string | undefined {
  const parts = [storeId !== 'sesoris' ? `store=${storeId}` : '', coupon ? `coupon=${coupon}` : ''].filter(Boolean);
  return parts.length ? parts.join(';').slice(0, 127) : undefined;
}

export function decodeCustomId(customId: string | undefined): { store: string; coupon?: string } {
  if (!customId) return { store: 'sesoris' };
  if (customId.startsWith('coupon:')) return { store: 'sesoris', coupon: customId.slice(7) };
  const kv = Object.fromEntries(customId.split(';').map((p) => p.split('=') as [string, string]));
  return { store: kv.store ?? 'sesoris', coupon: kv.coupon };
}
